# Generated by Django 4.2.7 on 2024-01-19 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Latest', 'Latest'), ('Politics', 'Politics'), ('Science', 'Science'), ('Crime', 'Crime'), ('Opinion', 'Opinion'), ('Education', 'Education'), ('Tourism', 'Tourism'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('General', 'General'), ('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Jobs', 'Jobs')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/media/uploads')),
                ('description', models.TextField()),
                ('publishing_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
