# Generated by Django 4.2.7 on 2024-01-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
