# Generated by Django 4.2.7 on 2024-01-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-rating']},
        ),
    ]
