# Generated by Django 4.2.7 on 2024-01-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating']},
        ),
    ]
