# Generated by Django 4.2.7 on 2024-01-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_rating_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='categories',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Science', 'Science'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology')], max_length=50),
        ),
    ]
