# Generated by Django 4.2.7 on 2024-01-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
    ]
