# Generated by Django 4.2.7 on 2024-01-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
