# Generated by Django 4.2.7 on 2024-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usernewspaperaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewspaperaccount',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
