# Generated by Django 5.0.2 on 2024-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usernewspaperaccount_is_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewspaperaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/media/uploads'),
        ),
    ]
