# Generated by Django 5.0.2 on 2024-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usernewspaperaccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewspaperaccount',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
