# Generated by Django 5.0.2 on 2024-04-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usernewspaperaccount_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernewspaperaccount',
            old_name='userImage',
            new_name='user_image',
        ),
    ]
