# Generated by Django 5.0.2 on 2024-04-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_userimage_usernewspaperaccount_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernewspaperaccount',
            old_name='user_image',
            new_name='userImage',
        ),
    ]
