# Generated by Django 5.0.2 on 2024-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usernewspaperaccount_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernewspaperaccount',
            name='userImage',
        ),
        migrations.AddField(
            model_name='usernewspaperaccount',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/static/profile_pics'),
        ),
    ]
