# Generated by Django 5.0.2 on 2024-04-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_editorrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditorRequest',
        ),
    ]
